/**
 * Privacy Policy Page
 * Privacy policy and data handling practices for S.A.G.E
 */

import React from 'react';
import {
  Box,
  Container,
  Typography,
  Paper,
  Divider,
} from '@mui/material';
import { PageHeader } from '../components/PageHeader';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <Box>
      <PageHeader
        title="Privacy Policy"
        subtitle="How we collect, use, and protect your information"
      />

      <Container maxWidth="md">
        <Paper sx={{ p: 4, mt: 3 }}>
          <Typography variant="body2" color="text.secondary" sx={{ mb: 4 }}>
            Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </Typography>

          <Typography variant="body1" paragraph>
            This Privacy Policy describes how S.A.G.E (Synthetic Audience Generation Engine) collects, uses, and protects your information when you use our service.
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ mt: 3, fontWeight: 600 }}>
            1. Information We Collect
          </Typography>

          <Typography variant="subtitle1" gutterBottom sx={{ mt: 2, fontWeight: 600 }}>
            1.1 Survey Data
          </Typography>
          <Typography variant="body1" paragraph>
            S.A.G.E collects and processes the following types of information:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Survey definitions you create (questions, categories, persona groups)
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Survey responses generated by AI models
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Configuration settings and preferences
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Usage statistics and system logs
            </Typography>
          </Box>

          <Typography variant="subtitle1" gutterBottom sx={{ mt: 2, fontWeight: 600 }}>
            1.2 Technical Information
          </Typography>
          <Typography variant="body1" paragraph>
            We automatically collect certain technical information when you use S.A.G.E:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Browser type and version
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Operating system
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              IP address (for system diagnostics only)
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Access times and dates
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            2. How We Use Your Information
          </Typography>
          <Typography variant="body1" paragraph>
            We use the information we collect to:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Provide and maintain the S.A.G.E service
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Generate synthetic survey responses using AI models
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Improve and optimize system performance
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Debug and resolve technical issues
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Conduct research and development for system improvements
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            3. Third-Party AI Services
          </Typography>
          <Typography variant="body1" paragraph>
            S.A.G.E integrates with third-party AI service providers including:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              OpenAI (GPT models)
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Anthropic (Claude models)
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Ollama (local models)
            </Typography>
          </Box>

          <Typography variant="body1" paragraph sx={{ mt: 2 }}>
            When you use S.A.G.E, your survey prompts and data may be sent to these external services for processing. Each provider has its own privacy policy and data handling practices:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              OpenAI Privacy Policy: https://openai.com/privacy
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Anthropic Privacy Policy: https://anthropic.com/privacy
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Ollama: Processes data locally on your infrastructure
            </Typography>
          </Box>

          <Typography variant="body1" paragraph sx={{ fontWeight: 500 }}>
            Important: You are responsible for reviewing and accepting the privacy policies of any third-party AI services you choose to use with S.A.G.E.
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            4. Data Storage and Security
          </Typography>
          <Typography variant="body1" paragraph>
            S.A.G.E stores survey data locally on your system or in your configured storage location. We implement reasonable security measures to protect your information:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Local file storage with appropriate access controls
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              YAML-based configuration for transparency and version control
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              No centralized data collection by default
            </Typography>
          </Box>

          <Typography variant="body1" paragraph sx={{ mt: 2 }}>
            However, no method of electronic storage is 100% secure. You are responsible for maintaining the security of your own API keys, credentials, and local data storage.
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            5. API Keys and Credentials
          </Typography>
          <Typography variant="body1" paragraph>
            S.A.G.E requires API keys to connect with third-party AI services. These credentials:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Are stored locally in your environment configuration
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Are never transmitted to S.A.G.E servers (as there are none)
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Should be kept confidential and rotated regularly
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Are your responsibility to manage and secure
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            6. Data Retention
          </Typography>
          <Typography variant="body1" paragraph>
            Survey data and responses are retained locally until you choose to delete them. S.A.G.E provides tools to:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Export survey data in CSV format
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Delete individual survey runs
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Manage survey definitions and configurations
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            7. Research and Academic Use
          </Typography>
          <Typography variant="body1" paragraph>
            If you use S.A.G.E for research purposes:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              You are responsible for obtaining necessary IRB approvals
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              You should follow your institution's data protection policies
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Synthetic responses should be clearly identified as AI-generated in publications
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              You must comply with applicable research ethics guidelines
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            8. Children's Privacy
          </Typography>
          <Typography variant="body1" paragraph>
            S.A.G.E is not intended for use by children under 13 years of age. We do not knowingly collect personal information from children under 13.
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            9. Your Rights and Choices
          </Typography>
          <Typography variant="body1" paragraph>
            You have the right to:
          </Typography>
          <Box component="ul" sx={{ pl: 4 }}>
            <Typography component="li" variant="body1" paragraph>
              Access your survey data at any time
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Export your data in standard formats
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Delete your data from the system
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Choose which AI providers to use
            </Typography>
            <Typography component="li" variant="body1" paragraph>
              Opt for local-only processing with Ollama
            </Typography>
          </Box>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            10. Changes to This Privacy Policy
          </Typography>
          <Typography variant="body1" paragraph>
            We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date.
          </Typography>

          <Divider sx={{ my: 3 }} />

          <Typography variant="h6" gutterBottom sx={{ fontWeight: 600 }}>
            11. Contact Us
          </Typography>
          <Typography variant="body1" paragraph>
            If you have questions about this Privacy Policy, please contact us at:
          </Typography>
          <Typography variant="body1" paragraph>
            Email: contact@example.com
          </Typography>
        </Paper>
      </Container>
    </Box>
  );
};

export default PrivacyPolicyPage;
